version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build: ../../services/api-gateway
    ports:
      - "3000:3000"

  auth:
    build: ../../services/auth-service
    ports:
      - "3001:3001"

  rust:
    build: ../../rust/signature-verifier
    ports:
      - "4000:4000"